name: Norminette

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Download norminette
      run: pip3 install norminette
    - name: Run norminette
      run: norminette
